name: Collect IMGW Data Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # co 10 minut
  workflow_dispatch:  # umożliwia ręczne uruchomienie

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python imgw_collector.py

      - name: Save results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: imgw-data
          path: data/
